// Pens
export const ANNOTATION_TOOL_PEN = "ANNOTATION_TOOL_PEN";
export const ANNOTATION_TOOL_HIGHLIGHTER = "ANNOTATION_TOOL_HIGHLIGHTER";
export const ANNOTATION_TOOL_ERASER = "ANNOTATION_TOOL_ERASER";

// Mode
export const ANNOTATION_MODE_ENABLED = "ANNOTATION_MODE_ENABLED";
export const ANNOTATION_MODE_DISABLED = "ANNOTATION_MODE_DISABLED";

// Metadata
export const ANNOTATION_SET_TOOL = "ANNOTATION_SET_TOOL";
export const ANNOTATION_SET_COLOR = "ANNOTATION_SET_COLOR";
export const ANNOTATION_SET_WIDTH = "ANNOTATION_SET_WIDTH";
export const ANNOTATION_TOGGLE_MODE = "ANNOTATION_TOGGLE_MODE";
export const ANNOTATION_CLEAR_ALL = "ANNOTATION_CLEAR_ALL";
