export const SCREEN_SHARE_START_REQUEST = "SCREEN_SHARE_START_REQUEST";
export const SCREEN_SHARE_START_SUCCESS = "SCREEN_SHARE_START_SUCCESS";
export const SCREEN_SHARE_START_FAILURE = "SCREEN_SHARE_START_FAILURE";
export const SCREEN_SHARE_STOP_REQUEST = "SCREEN_SHARE_STOP_REQUEST";
export const SCREEN_SHARE_STOP_SUCCESS = "SCREEN_SHARE_STOP_SUCCESS";
